// frontend/src/redux/actionTypes.js
export const GENERATE_AUDIO_REQUEST = 'GENERATE_AUDIO_REQUEST';
export const GENERATE_AUDIO_PROGRESS = 'GENERATE_AUDIO_PROGRESS';
export const GENERATE_AUDIO_SUCCESS = 'GENERATE_AUDIO_SUCCESS';
export const GENERATE_AUDIO_FAILURE = 'GENERATE_AUDIO_FAILURE';

export const SET_TEXT_INPUT = 'SET_TEXT_INPUT';
export const SET_EVENTS_CHANNEL = 'SET_EVENTS_CHANNEL';
export const CLEAR_EVENTS_CHANNEL = 'CLEAR_EVENTS_CHANNEL';
export const RESET_GENERATION_STATE = 'RESET_GENERATION_STATE';
